---
# Define Docker Compose version.
version: "3.2"

# Define all the containers.
services:
  # Backend Container
  backend:
    ports:
      - ${APP_PORT}:3001
  # Frontend Container with Frontend Docs.
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./app/frontend:/usr/src/app
    environment:
      NODE_ENV: ${APP_ENV}
    command: /usr/src/app/entrypoint.sh
  # Api Documentation Container.
  #api-documentation:
  #  build: ./app/docs
  #  environment:
  #    BASE_URL: tattoo-platform.redvike.rocks
  #  volumes:
  #    - ./app/docs:/usr/src/docs
  #  ports:
  #    - ${DOCS_PORT}:3002
  #  command: /usr/src/docs/entrypoint.sh
