# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc 'Build and upload to App Center.'
  lane :beta do
  build
  appcenter_upload(
    api_token: "5616607d73245e24281893dc7fcce66553984842",
    owner_name: "MarekMeissner",
    app_name: "Podcaster-1",
    apk: "./app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: './')
    gradle(task: 'assemble', build_type: 'release', project_dir: './')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end