defaults: &defaults
  working_directory: ~/podcaster/app/frontend
  docker:
    - image: circleci/node:10.15.1
  environment:
    REACT_APP_API: http://localhost:3001

version: 2

jobs:
  backend-docker:
    machine: true
    working_directory: ~/podcaster
    steps:
      - checkout:
          path: ~/podcaster
      - run:
          name: Create docker env variables
          command: echo -e "APP_PORT=$APP_PORT" > .env
      - run:
          name: Copy CircleCI env variables to backend docker
          command: cd app/backend && echo -e "DB_URL=$DB_URL\nSENTRY_DSN=$SENTRY_DSN\nJSON_CONTENT_LIMIT=$JSON_CONTENT_LIMIT\nBCRYPT_SALT=$BCRYPT_SALT\nJWT_SECRET=$JWT_SECRET\n" > .env
      - run:
          name: Build docker container
          command: docker-compose -f docker-compose.yml -f docker-compose.development.yml up --build -d
      - run:
          name: Linter check
          command: docker-compose exec backend npx eslint src/** seed/** --ext .ts
      - run:
          name: Tests check
          command: docker-compose exec backend npm run test
  
  prepare:
    <<: *defaults
    steps:
      - checkout:
          path: ~/podcaster

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - .cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

  android-test:
    working_directory: ~/podcaster/app/frontend/android
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:
          path: ~/podcaster/app/frontend/

      - attach_workspace:
          at: ~/podcaster/app/frontend/

      - restore_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run: bundle install

      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android-beta:
    working_directory: ~/podcaster/app/frontend/android
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:
          path: ~/podcaster/app/frontend/

      - attach_workspace:
          at: ~/podcaster/app/frontend/

      - restore_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run: bundle install

      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane build beta
          command: |
            bundle exec fastlane beta

  ios:
    macos:
      xcode: "9.0"
    working_directory: ~/podcaster/app/frontend/

    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - run:
          name: set Ruby version
          command:  echo "ruby-2.4" > ~/.ruby-version

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      # not using a workspace here as Node and Yarn versions
      # differ between our macOS executor image and the Docker containers above
      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v2-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run:
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v2-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          command: bundle exec fastlane test
          working_directory: ios

      - run:
          name: set up test results
          working_directory: ios
          when: always
          command: |
            mkdir -p test-results/fastlane test-results/xcode
            mv fastlane/report.xml test-results/fastlane
            mv fastlane/test_output/report.junit test-results/xcode/junit.xml
      - store_test_results:
          path: ios/test-results

      - store_artifacts:
          path: ios/test-results

workflows:
  version: 2
  node-android-ios:
    jobs:
      - backend-docker
      - prepare
      - android-test:
          requires:
            - prepare
          filters:
            branches:
              ignore: develop
      - android-beta:
          requires:
            - prepare
          filters:
            branches:
              only: develop
#      - ios:
#          requires:
#            - node
