name: Android-beta-deploy

on:
  push:
    tags:
      - betaAndroid*

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./app/node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('**/yarn.lock') }}

      - name: install packages
        run: |
          cd app
          yarn

      - name: run fastlane
        run: |
          cd app
          yarn deploy:android