name: Frontend

on: 
  push:
    branches:    
      - '*'
jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run lint
    - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}

    - run: |
        cd app
        yarn

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - save_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
        paths:
          - node_modules
    
    - run: 
        name: eslint
        command: yarn lint
        
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
    - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}

    - run: |
        cd app
        yarn

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - save_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
        paths:
          - node_modules
    
    - run: 
        name: jest tests
        command: yarn test
