name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run lint
      run: |
        cd app/frontend
        yarn
        yarn lint
        
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        cd app/frontend
        yarn
        yarn test
